config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  match 'main/register',to: 'main#register' , as: :register , via: [:get , :post]
  get 'session/new'
  get 'main/:rooms_name/:room_id' , to: 'main#chat_room', as: :chat
  post 'session/create' ,to: 'session#create' , as: :session_create
  delete 'session/delete', to: 'session#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
   mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  self.table_name = 'posts'
  belongs_to :user
  belongs_to :room

  after_create_commit { ChatBroadcastJob.perform_later self }
end

app/models/room.rb
class Room < ApplicationRecord

has_many :chats

end

app/models/user.rb
class User < ApplicationRecord
  self.table_name = "users"
  has_many :chats

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def signed_in?
    current_user.present?
  end
  helper_method :signed_in?


  private
  def authenticate!
    redirect_to session_new_path and return unless signed_in?
  end

  def check_signed?
    redirect_to root_path if signed_in?
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate! , except: :register
  before_action :check_signed? , only: :register
  def index
    @user = current_user
    @chat = Chat.order('created_at').joins(:user)
  end

  def register
    if request.post?
      User.transaction do
          user = User.create!(name: params[:register][:name] )
         puts  params
          if !params[:register][:room_name].nil?
            room = Room.create!(name: params[:register][:room_name])
          else
            room = "public"
          end
          if user.save
            session[:user_id] = user.id
            redirect_to  chat_path(rooms_name: room)
          else
            redirect_to register_path
          end
      end
    end
  end

  def chat_room
    @room = Room.find_by name: params[:rooms_name]
    if @room.present?
    @user = current_user
    @chat = Chat.joins(:room,:user)
                .where("rooms.id = #{@room.id}")
                .order('created_at')

    else @room.nil?
      flash[:alert] = 'The chat room doesnt exist you have to create it'
      redirect_to session_new_path
    end
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :check_signed? , except: :destroy
  def new
    @user = User.new
    @room = Room.all
  end

  def create
     user = User.find_by(name: params[:name])
     if user.present?
       session[:user_id] = user.id
       room = params[:rooms_name].nil? ? 'public' : params[:rooms_name]
       @room_id = Room.find_by(name: room)
       redirect_to chat_path(rooms_name: room,room_id: @room_id.id)
     else
       redirect_to session_new_path
     end
  end

  def destroy
    session[:user_id] = nil
    redirect_to session_new_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/chats/_chat.html.erb
<p id="new1">
<%= chat.user.name %> : <%= chat.data %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twilio</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/chat_room.html.erb
<%= link_to 'Sign Out', session_delete_path , method: :delete%>
<p>
  <%= @user.name %>
</p>

<div id="messages" data-room="<%= params[:rooms_name] %>">
</div>
<%= render @chat %>

<form>
  <input type="text" id="message1">
  <input type="hidden" id="userId1" value="<%= @user.id %>">
  <input type="hidden" id="chatRoom" value="<%= params[:room_id] %>">

  <button id="btn1">Send</button>

</form>

app/views/main/index.html.erb
<%= link_to 'Sign Out', session_delete_path , method: :delete%>
<p>
  <%= @user.name %>
</p>

<%= render @chat %>

<form>
  <input type="text" id="message1">
  <input type="hidden" id="userId1" value="<%= @user.id %>">
  <button id="btn1">Send</button>

</form>

app/views/main/register.html.erb
<%= form_for :register do |f| %>
  name : <%= f.text_field :name %>
  room Name : <%= f.text_field :room_name %>
  <%= f.submit  %>
<% end %>

app/views/session/new.html.erb
<h5>sign in</h5>


<%= form_tag session_create_path do %>
    <%= label_tag(:name, "name:") %>
    <%= text_field_tag(:name) %><br>
    <%= label_tag(:room_name, "Room Name :") %>
    <%= text_field_tag(:room_name) %><br>
    <%= submit_tag("Enter Room") %>
<% end %>

<h4>Current Rooms</h4>
<% @room.each do |f|  %>
 <br>Current Active Rooms <b><%= f.name  %></b>
<% end %><br><br>

<%= link_to 'sign up' , register_path %>